### ISSUE TITLE
Readme  Front-end checklist

### ISSUE THREAD

**Issue by yenpraja610** [squad-of-war/magic-box#17]
- [x] A short description of your application.

- [x] A brief explanation of the technologies (Node modules, Express middleware etc) used.

- [x] A couple of paragraphs detailing the general approach you took.

- [x] Notes on any unsolved problems or major hurdles your team had to overcome.
    
- [x] Installation instructions for any dependencies.

- [x] A link to your user stories – who are your users, what do they want, and why?

- [x] A link to your ERD - what data models does your app use?

- [x] A link to your wireframes – sketches of major views / interfaces in your application.

- [x] A link to the deployed front-end app.

- [x] A link to the repo for your back-end.

**Comment by yenpraja610** [comment]
:)
