### ISSUE TITLE
User Uploads

### ISSUE THREAD

**Issue by ddobson** [squad-of-war/magic-box#4]
As a user I should be able to perform CRUD actions on a file upload. I should be able to upload any type of file.

**Tasks**
- [x]  Model an Upload Resource
- [x] Write CURL scripts for testing API endpoints
- [x]  Create routes for basic CRUD functions
- [x]  Create Controller actions for each CRUD function
- [x] CRUD actions should have a corresponding action on S3
- [x]  Client-side events and AJAX for each CRUD action
- [x] Client-side validations

**Comment by Sofistication** [comment]
This can be closed, correct?
